name = "jewelry-proposal-app"
pages_build_output_dir = "dist"
compatibility_date = "2025-12-01"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "jewelry_proposals"
database_id = "8628756d-03e2-4ace-8a03-94250e5c364f"
